version: "3"
networks:
  test:
services:
  webserver:
    build:
      context: ./services/${PHPVERSION}
    container_name: '${COMPOSE_PROJECT_NAME}-${PHPVERSION}'
    restart: 'always'
    networks:
      - test
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/html
